server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  cache:
    type: redis
    redis:
      time-to-live: 3600 # 데이터 유지 시간(sec)
      cache-null-values: true # null 캐싱 여부
      host: localhost
      port: 8080

  mvc:
    view:
      prefix: /templates/
      suffix: .mustache

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true # sql 출력
    hibernate:
      ddl-auto: update  # create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost #배포서버일 경우 loalhost가 아닌 ec2 주소 사용
      port: 6379

jwt:
  secret: TXlTV1Byb2plY3RVc2luZ0pXVHdpdGhTcHJpbmdCb290QW5kU3ByaW5nU2VjdXJpdHk= # 임의의 문자열을 Base64로 인코딩한 값
  refresh-token-validity-in-seconds : 604800  # 7일
  access-token-validity-in-second : 10800   # 3시간