### get all boards
GET http://localhost:8080/boards


### get all boards by paging
GET http://localhost:8080/boards/paging?page=0&size=5


### get post counts
GET http://localhost:8080/boards/counts


# intelli http에서 multipart/form_data를 보내는 방법
# https://m.blog.naver.com/PostView.naver?blogId=rinjyu&logNo=222156997603&categoryNo=34&proxyReferer=

### create post
POST http://localhost:8080/boards
Content-Type: multipart/form-data; boundary=createPostBoundary

--createPostBoundary
Content-Disposition: form-data; name="mem_id"

유저아이디입니다.

--createPostBoundary
Content-Disposition: form-data; name="title"

제목입니다.

--createPostBoundary
Content-Disposition: form-data; name="text"

내용입니다.

--createPostBoundary
Content-Disposition: form-data; name="files"; filename="createPostTestFile1.txt"

< ./createPostTestFile1.txt

--createPostBoundary
Content-Disposition: form-data; name="files"; filename="createPostTestFile2.txt"

< ./createPostTestFile2.txt

--createPostBoundary
Content-Disposition: form-data; name="files"; filename="img.png"

< ./

### test
POST http://localhost:8080/login
Content-Type: application/json

{
  "memberID": "b@b.com",
  "memberPW": "b"
}


### test
GET http://localhost:8080/joinForm
Authorization: Bearer eyJyZWdEYXRlIjoxNzAxNjU5NTg3MDYyLCJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJtZW1iZXJOYW1lIjoiYiIsImV4cCI6MTcwNDI1MTU4NywibWVtYmVySUQiOiJiQGIuY29tIn0.b95p5hWUG7Ct-SkDlGIyAsLbjXTOMab0aLPOE2B6eVQ


### 게시글 조회
GET http://localhost:8080/boards
Authorization: Bearer eyJyZWdEYXRlIjoxNzAxNjU5NTg3MDYyLCJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJtZW1iZXJOYW1lIjoiYiIsImV4cCI6MTcwNDI1MTU4NywibWVtYmVySUQiOiJiQGIuY29tIn0.b95p5hWUG7Ct-SkDlGIyAsLbjXTOMab0aLPOE2B6eVQ


### 게시글 생성
POST http://localhost:8080/boards
Authorization: Bearer eyJyZWdEYXRlIjoxNzAxNjU5NTg3MDYyLCJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJtZW1iZXJOYW1lIjoiYiIsImV4cCI6MTcwNDI1MTU4NywibWVtYmVySUQiOiJiQGIuY29tIn0.b95p5hWUG7Ct-SkDlGIyAsLbjXTOMab0aLPOE2B6eVQ
Content-Type: application/json

{
  "title": "제목입니다.",
  "content": "내용입니다."
}


### 게시글 수정
PUT http://localhost:8080/boards/15
Authorization: Bearer eyJyZWdEYXRlIjoxNzAxODIyMjQ5MTA5LCJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJtZW1iZXJOYW1lIjoiYiIsImV4cCI6MTcwNDQxNDI0OSwibWVtYmVySUQiOiJiQGIuY29tIn0.2SNUIPSbtJNuPMBXUrZBcU3uIFopvRn8T0bPsN5qtjI
Content-Type: application/json

{
  "title": "수정된 제목입니다.",
  "content": "수정된 내용입니다."
}


### 게시글 삭제
DELETE http://localhost:8080/boards/15
Authorization: Bearer eyJyZWdEYXRlIjoxNzAxODIyMjQ5MTA5LCJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJtZW1iZXJOYW1lIjoiYiIsImV4cCI6MTcwNDQxNDI0OSwibWVtYmVySUQiOiJiQGIuY29tIn0.2SNUIPSbtJNuPMBXUrZBcU3uIFopvRn8T0bPsN5qtjI


### 댓글 생성
POST http://localhost:8080/boards/14/replies
Authorization: Bearer eyJyZWdEYXRlIjoxNzAxNjU5NTg3MDYyLCJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJtZW1iZXJOYW1lIjoiYiIsImV4cCI6MTcwNDI1MTU4NywibWVtYmVySUQiOiJiQGIuY29tIn0.b95p5hWUG7Ct-SkDlGIyAsLbjXTOMab0aLPOE2B6eVQ
Content-Type: application/json

{
  "content": "내용입니다."
}
