### get all boards
GET http://localhost:8080/boards


### login
POST http://localhost:8080/login
Content-Type: application/json

{
  "memberID": "b@b.com",
  "memberPW": "b"
}

> {%
    client.test("Validate", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.accessToken.trim().length > 0);
        client.assert(response.body.refreshToken.trim().length > 0);
    });

    client.log(response.body.accessToken);
    client.global.set("access_token", 'Bearer '.concat(response.body.accessToken));
    client.global.set("refresh_token", response.body.refreshToken);
 %}


### login2
POST http://localhost:8080/login?memberID=b@b.com&memberPW=b
Content-Type: application/x-www-form-urlencoded

> {%
    client.test("Validate", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.accessToken.trim().length > 0);
        client.assert(response.body.refreshToken.trim().length > 0);
    });

    client.log(response.body.accessToken);
    client.global.set("access_token", 'Bearer '.concat(response.body.accessToken));
    client.global.set("refresh_token", response.body.refreshToken);
%}


### reissue
POST http://localhost:8080/reissue
Content-Type: application/json
Authorization: {{access_token}}
Refresh-Token: {{refresh_token}}


### user list
GET http://localhost:8080/user/list
Authorization: {{access_token}}


### 게시글 조회
GET http://localhost:8080/boards
Authorization: {{access_token}}


### 게시글 생성
POST http://localhost:8080/boards
Authorization: {{access_token}}
Content-Type: application/json

{
  "title": "제목입니다.",
  "content": "내용입니다."
}


### 게시글 수정
PUT http://localhost:8080/boards/15
Content-Type: application/json

{
  "title": "수정된 제목입니다.",
  "content": "수정된 내용입니다."
}


### 게시글 삭제
DELETE http://localhost:8080/boards/15
Authorization: {{access_token}}


### 댓글 생성
POST http://localhost:8080/boards/14/replies
Authorization: {{access_token}}
Content-Type: application/json

{
  "content": "내용입니다."
}
