= SSO Project Documentation
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:


== 로그인

operation::login-controller-test/login[snippets="http-request,form-parameters,http-response,response-headers"]


== 회원가입

operation::login-controller-test/signup[snippets="http-request,form-parameters"]


== 게시글 조회

- page 기본값: 0, size 기본값: 10

operation::post-controller-test/get-all-boards[snippets="http-request,query-parameters,response-body,response-fields"]

== 게시글 단건 조회

operation::post-controller-test/find-board[snippets="http-request,path-parameters,response-body,response-fields"]

== 게시글 생성

operation::post-controller-test/create-board[snippets="http-request,request-headers,request-fields,response-body"]

== 게시글 수정

operation::post-controller-test/edit-board[snippets="http-request,path-parameters,request-headers,request-fields,response-body"]

== 게시글 삭제

operation::post-controller-test/delete-board[snippets="http-request,path-parameters,request-headers,response-body"]


== 댓글 조회

- page 기본값: 0, size 기본값: 10

operation::reply-controller-test/get-all-replies[snippets="http-request,path-parameters,query-parameters,response-body,response-fields"]

== 댓글 생성

operation::reply-controller-test/create-reply[snippets="http-request,path-parameters,request-headers,request-fields,http-response"]
