= SSO Project Documentation
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:


== 로그인

=== Form으로 로그인
operation::login-controller-test/login-by-www[snippets="http-request,form-parameters,http-response,response-fields"]

=== Json으로 로그인
operation::login-controller-test/login-by-json[snippets="http-request,request-fields,http-response,response-fields"]

== 회원가입

operation::login-controller-test/signup[snippets="http-request,form-parameters"]


== 토큰 재발급

operation::login-controller-test/reissue[snippets="http-request,request-headers,http-response,response-fields"]


== 로그인한 사용자 정보 조회

operation::login-controller-test/login-status-check[snippets="http-request,request-headers,http-response,response-fields"]


== 게시글 조회

- page 기본값: 0, size 기본값: 10

operation::post-controller-test/get-all-boards[snippets="http-request,query-parameters,response-body,response-fields"]

== 게시글 단건 조회

operation::post-controller-test/find-board[snippets="http-request,path-parameters,response-body,response-fields"]

== 게시글 생성

IMPORTANT: "권한 변경" 문구는 제목에 포함할 수 없습니다.

operation::post-controller-test/create-board[snippets="http-request,request-headers,request-fields,http-response"]

== 게시글 수정 - 작성자 권한

IMPORTANT: 작성자만 권한이 존재합니다.

operation::post-controller-test/edit-board[snippets="http-request,path-parameters,request-headers,request-fields,http-response"]

== 게시글 삭제

operation::post-controller-test/delete-board[snippets="http-request,path-parameters,request-headers,http-response"]

== 권한 변경 게시글 생성

operation::post-controller-test/create-role-change-board[snippets="http-request,request-headers,request-fields,http-response"]


== 댓글 조회

- page 기본값: 0, size 기본값: 10

operation::reply-controller-test/get-all-replies[snippets="http-request,path-parameters,query-parameters,response-body,response-fields"]

== 댓글 생성

operation::reply-controller-test/create-reply[snippets="http-request,path-parameters,request-headers,request-fields,http-response"]

== 댓글 수정 - 작성자 권한

IMPORTANT: 작성자만 권한이 존재합니다.

operation::reply-controller-test/edit-reply[snippets="http-request,path-parameters,request-headers,request-fields,http-response"]

== 댓글 삭제

operation::reply-controller-test/delete-reply[snippets="http-request,path-parameters,request-headers,http-response"]
